<template>
  <v-row
          align="center"
          justify="center"
        >
        <v-col
            cols="12"
            sm="8"
            md="4"
            class="text-center"
          >
          <h1>Dashboard</h1>
        </v-col>
  </v-row>
</template>
